pipeline {
    agent any
    environment {
        DOCKER_COMPOSE_FILE = 'docker-compose.yml'
    }
    stages {
        stage('Checkout Code') {
            steps {
                git 'https://github.com/mohamednaffeti/customer-service.git'
            }
        }
        stage('Build Application') {
            steps {
                sh './mvnw clean package -DskipTests' // Compile et package l'application
            }
        }
        stage('Run Tests') {
            steps {
                sh './mvnw test' // Exécute les tests unitaires
            }
        }
        stage('Build Docker Image') {
            steps {
                sh 'docker build -t enset-customer-service .'
            }
        }
        stage('Deploy with Docker Compose') {
            steps {
                sh 'docker-compose up -d'
            }
        }
    }
    post {
        always {
            echo 'Pipeline terminé'
        }
        success {
            echo 'Build et déploiement réussis !'
        }
        failure {
            echo 'Une erreur s\'est produite lors du pipeline.'
        }
    }
}
